version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "开始安装依赖信息"
      - run: npm install
      - run: echo "开始测试信息"
      - run: npm run test
      - run: echo "开始打包"
      - run: npm run build
      - run: echo "打包成功"
workflows:
  node-tests:
    jobs:
      - build
